### ISSUE TITLE
Unable to run on Linux

### ISSUE THREAD

**Issue by GRClark** [TekniskSupport/ST-zigbee-network-map#2]
Starts fine and pulls devices but at the end of it's run it gives the following error:

`Traceback (most recent call last):
  File "/home/grclark/ST-zigbee-network-map/scrape-st.py", line 1, in <module>
    import _scrape
  File "/home/grclark/ST-zigbee-network-map/_scrape.py", line 108, in <module>
    nx.draw(G,**options)
  File "/home/grclark/.local/lib/python2.7/site-packages/networkx/drawing/nx_pylab.py", line 106, in draw
    raise ImportError("Matplotlib required for draw()")
ImportError: Matplotlib required for draw()`

Running this on Linux Mint 20.3 using the command
`python /ST-zigbee-network-map/scrape-st.py`

**Comment by TekniskSupport** [comment]
You  are missing dependencies, did you install them using the command below?

`python -m pip install matplotlib bs4 networkx requests`?
